force-app/main/default/objects/IpAddressAnomoly__c/IpAddressAnomoly__c.object-meta.xml
<CustomObject>
    <label>IP Address Anomoly</label>
    <nameField>
        <displayFormat>IPAA-{00000}</displayFormat>
        <label>IpAddressAnomoly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IP Address Anomolies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IpAddressAnomoly__c/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <description>The time of the specified event. For example, 2020-01-20T19:12:26.965Z. Milliseconds are the most granular setting.</description>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IpAddressAnomoly__c/fields/EventIdentifier__c.field-meta.xml
<CustomField>
    <fullName>EventIdentifier__c</fullName>
    <description>The unique identifier for each record in Event. Use this field as the primary key in your queries.</description>
    <label>Event Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IpAddressAnomoly__c/fields/LoginDate__c.field-meta.xml
<CustomField>
    <fullName>LoginDate__c</fullName>
    <description>The login time of the specified event. For example, 2020-01-20T19:12:26.965Z. Milliseconds are the most granular setting.</description>
    <label>Login Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IpAddressAnomoly__c/fields/LoginHistoryId__c.field-meta.xml
<CustomField>
    <fullName>LoginHistoryId__c</fullName>
    <label>Login History Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IpAddressAnomoly__c/fields/LoginKey__c.field-meta.xml
<CustomField>
    <fullName>LoginKey__c</fullName>
    <label>Login Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IpAddressAnomoly__c/fields/LoginType__c.field-meta.xml
<CustomField>
    <fullName>LoginType__c</fullName>
    <label>Login Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IpAddressAnomalyHandler.cls
/**
 *
 */
public class IpAddressAnomalyHandler implements Queueable {
  private LoginHistory loginHistory;
  private SObject ipEvent;

  /**
   * @description IpAddressAnomalyHandler description
   * @param  loginHistory loginHistory description
   * @param  ipEvent      ipEvent description
   * @return              return description
   */
  public IpAddressAnomalyHandler(LoginHistory loginHistory, SObject ipEvent) {
    this.loginHistory = loginHistory;
    this.ipEvent = ipEvent;
  }
  /**
   * @description execute description
   * @param  context context description
   */
  public void execute(QueueableContext context) {
    IpAddressAnomoly__c ipAnomoly = new IpAddressAnomoly__c();
    ipAnomoly.EventDate__c = (DateTime) ipEvent.get('EventDate');
    ipAnomoly.EventIdentifier__c = (String) ipEvent.get('EventIdentifier');
    ipAnomoly.EventIp__c = (String) ipEvent.get('SourceIp');
    ipAnomoly.LoginApplication__c = loginHistory.Application;
    ipAnomoly.LoginDate__c = loginHistory.LoginTime;
    ipAnomoly.LoginHistoryId__c = loginHistory.Id;
    ipAnomoly.LoginIp__c = loginHistory.SourceIp;
    ipAnomoly.LoginKey__c = (String) ipEvent.get('LoginKey');
    ipAnomoly.LoginType__c = loginHistory.LoginType;
    ipAnomoly.SessionKey__c = (String) ipEvent.get('SessionKey');
    ipAnomoly.User__c = (Id) ipEvent.get('UserId');
    ipAnomoly.EventType__c = getEventType();
    insert ipAnomoly;
  }
  /**
   * @description getEventType description
   * @return   return description
   */
  private String getEventType() {
    switch on ipEvent {
      when ApiEvent ev {
        return 'ApiEvent';
      }
      when BulkApiResultEvent ev {
        return 'BulkApiResultEvent';
      }
      when ListViewEvent ev {
        return 'ListViewEvent';
      }
      when ReportEvent ev {
        return 'ReportEvent';
      }
      when else {
        return 'unkown';
      }
    }
  }
}